const itemsData = [
  { id: 1, nombre: 'Cemento', descripcion: 'Bolsa de cemento 50kg', stock: 20, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '001' },
  { id: 2, nombre: 'Arena', descripcion: 'Bolsa de arena 50kg', stock: 15, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '002' },
  { id: 3, nombre: 'Ladrillos', descripcion: 'Ladrillo hueco 12x18x33', stock: 500, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '003' },
  { id: 4, nombre: 'Hierro', descripcion: 'Varilla de hierro 6mm', stock: 300, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '004' },
  { id: 5, nombre: 'Cal', descripcion: 'Bolsa de cal 25kg', stock: 50, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '005' },
  { id: 6, nombre: 'Grava', descripcion: 'Bolsa de grava 50kg', stock: 40, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '006' },
  { id: 7, nombre: 'Pintura', descripcion: 'Lata de pintura blanca 10L', stock: 60, categoria: 'Materiales', subcategoria: 'Pinturas', numeroOrden: '007' },
  { id: 8, nombre: 'Yeso', descripcion: 'Bolsa de yeso 20kg', stock: 80, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '008' },
  { id: 9, nombre: 'Tejas', descripcion: 'Teja colonial', stock: 200, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '009' },
  { id: 10, nombre: 'Aditivo impermeabilizante', descripcion: 'Botella de 1L', stock: 30, categoria: 'Materiales', subcategoria: 'Químicos', numeroOrden: '010' },
  { id: 11, nombre: 'Cemento cola', descripcion: 'Bolsa de 25kg', stock: 100, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '011' },
  { id: 12, nombre: 'Madera', descripcion: 'Tablón de pino 2x4', stock: 150, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '012' },
  { id: 13, nombre: 'Clavos', descripcion: 'Caja de clavos 1kg', stock: 500, categoria: 'Materiales', subcategoria: 'Ferretería', numeroOrden: '013' },
  { id: 14, nombre: 'Tornillos', descripcion: 'Caja de tornillos 1kg', stock: 450, categoria: 'Materiales', subcategoria: 'Ferretería', numeroOrden: '014' },
  { id: 15, nombre: 'Cañería PVC', descripcion: 'Cañería PVC 2 pulgadas', stock: 100, categoria: 'Materiales', subcategoria: 'Plomería', numeroOrden: '015' },
  { id: 16, nombre: 'Cable eléctrico', descripcion: 'Rollo de cable 100m', stock: 75, categoria: 'Materiales', subcategoria: 'Electricidad', numeroOrden: '016' },
  { id: 17, nombre: 'Llave inglesa', descripcion: 'Llave inglesa 12 pulgadas', stock: 35, categoria: 'Herramientas', subcategoria: 'Manuales', numeroOrden: '017' },
  { id: 18, nombre: 'Martillo', descripcion: 'Martillo carpintero', stock: 40, categoria: 'Herramientas', subcategoria: 'Manuales', numeroOrden: '018' },
  { id: 19, nombre: 'Taladro', descripcion: 'Taladro eléctrico', stock: 20, categoria: 'Herramientas', subcategoria: 'Eléctricas', numeroOrden: '019' },
  { id: 20, nombre: 'Lija', descripcion: 'Papel de lija grano 120', stock: 200, categoria: 'Materiales', subcategoria: 'Pinturas', numeroOrden: '020' },
  { id: 21, nombre: 'Pala', descripcion: 'Pala ancha', stock: 25, categoria: 'Herramientas', subcategoria: 'Manuales', numeroOrden: '021' },
  { id: 22, nombre: 'Cinta métrica', descripcion: 'Cinta métrica 5m', stock: 70, categoria: 'Herramientas', subcategoria: 'Manuales', numeroOrden: '022' },
  { id: 23, nombre: 'Sierra', descripcion: 'Sierra manual', stock: 30, categoria: 'Herramientas', subcategoria: 'Manuales', numeroOrden: '023' },
  { id: 24, nombre: 'Espejo', descripcion: 'Espejo de baño 60x80cm', stock: 50, categoria: 'Materiales', subcategoria: 'Baños', numeroOrden: '024' },
  { id: 25, nombre: 'Azulejos', descripcion: 'Azulejos 20x20cm', stock: 250, categoria: 'Materiales', subcategoria: 'Baños', numeroOrden: '025' },
  { id: 26, nombre: 'Cemento rápido', descripcion: 'Bolsa de cemento rápido 5kg', stock: 100, categoria: 'Materiales', subcategoria: 'Construcción', numeroOrden: '026' },
  { id: 27, nombre: 'Válvula de agua', descripcion: 'Válvula de agua 1 pulgada', stock: 70, categoria: 'Materiales', subcategoria: 'Plomería', numeroOrden: '027' },
  { id: 28, nombre: 'Llaves de paso', descripcion: 'Llave de paso 1 pulgada', stock: 60, categoria: 'Materiales', subcategoria: 'Plomería', numeroOrden: '028' },
  { id: 29, nombre: 'Tubería de cobre', descripcion: 'Tubería de cobre 1 pulgada', stock: 50, categoria: 'Materiales', subcategoria: 'Plomería', numeroOrden: '029' },
  { id: 30, nombre: 'Masilla', descripcion: 'Bote de masilla 1kg', stock: 100, categoria: 'Materiales', subcategoria: 'Pinturas', numeroOrden: '030' }
];

export default itemsData;
